### ISSUE TITLE
Faux positif sur les espaces entre type et nom de function

### ISSUE THREAD

**Issue by Emeraude** [sebastiencs/moulinette#4]
Dans certains cas, la moulinette nous sort l'erreur `Utilisation d'espace entre le type et le nom de la variable/fonction` sans raison.

Voici une liste non exhaustive des cas d'erreurs :

``` C
inline char toto(void);
inline __attribute__ ((always_inline)) char toto(void);
/* Ou bien avec des macros */
#define INLINE inline __attribute__ ((always_inline))
INLINE char toto(void);
```

**Comment by sebastiencs** [comment]
J'ai corriger pour les 2 premiers cas.
Pour les macros je peux pas gerer ce cas la
